# Generated by Django 2.2.1 on 2019-12-06 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Sertanejo, Clássica, Internacional, MPB', max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Estilo',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Como é grande o meu amor por voce, Incondicional, A lenda, You and I', max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Sertanejo, Clássica, Internacional, MPB', max_length=250, verbose_name='Descrição')),
                ('nome', models.CharField(blank=True, help_text='Nome da Música?', max_length=50, null=True)),
                ('autor', models.CharField(blank=True, help_text='Nome do autor?', max_length=50, null=True)),
                ('foto', models.URLField(help_text='Informe a URL de uma imagem para este animal. Ex: http://...')),
                ('ano', models.CharField(max_length=5)),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aulas.Estilo', verbose_name='Estilo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aulas.Tipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, help_text='Espaço para colocar qualquer informação.', null=True, verbose_name='Descrição')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aulas.Estado')),
            ],
        ),
    ]
