# Generated by Django 2.2.1 on 2019-12-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_auto_20191206_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='foto',
        ),
    ]
